"""Add database Authors

Revision ID: 4eae2a6fe94c
Revises: 84614584214f
Create Date: 2022-03-12 00:28:05.613394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eae2a6fe94c'
down_revision = '84614584214f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
