"""Add column is_staff to User

Revision ID: 84614584214f
Revises: 4e4d27381119
Create Date: 2022-03-12 00:23:36.637961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84614584214f'
down_revision = '4e4d27381119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_users',
    sa.Column('is_staff', 
    sa.Boolean(),
    server_default='FALSE', 
    nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_users', 'is_staff')
    # ### end Alembic commands ###
