"""Authors is connected to user

Revision ID: f046edd79065
Revises: 4eae2a6fe94c
Create Date: 2022-03-12 00:29:42.193023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f046edd79065'
down_revision = '4eae2a6fe94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
