# Generated by Django 3.2 on 2022-04-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('animal', models.ManyToManyField(to='animals.Animal')),
            ],
        ),
    ]
